version: '3'
services:
  api:
    build: .
    command: "node teletriade.js"
    environment:
      - NODE_ENV=production
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - rede-triade
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3002"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  bot:
    build: .
    command: ["bash", "-c", "sleep 30 && python teletriade.py"]
    depends_on:
      api:
        condition: service_healthy
    networks:
      - rede-triade
    restart: always

networks:
  rede-triade:
    external: true
    name: rede-triade
