version: '3'
services:
  api:
    build: .
    command: "node teletriade.js"
    working_dir: /app/telegram/api
    environment:
      - NODE_ENV=production
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - rede-triade
    restart: always

  bot:
    build: .
    command: "python teletriade.py"
    working_dir: /app/telegram/bot
    depends_on:
      - api
    networks:
      - rede-triade
    restart: always

networks:
  rede-triade:
    external: true
    name: rede-triade
