version: '3'
services:
  triade:
    build: .
    command: ["bash", "-c", "node api/teletriade.js & python bot/teletriade.py"]
    environment:
      - NODE_ENV=production
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - rede-triade
    restart: always

networks:
  rede-triade:
    external: true
    name: rede-triade