version: '3'
services:
  api:
    build: .
    command: "node teletriade.js"
    environment:
      - NODE_ENV=production
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - rede-triade
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m

  bot:
    build: .
    command: "python teletriade.py"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - rede-triade
    restart: always

networks:
  rede-triade:
    external: true
    name: rede-triade
