version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: "node teletriade.js"
    environment:
      - NODE_ENV=production
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - rede-triade
    restart: always
    
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    command: ["bash", "-c", "sleep 30 && python teletriade3.py"]
    networks:
      - rede-triade
    restart: always

networks:
  rede-triade:
    external: true
    name: rede-triade
