# Dockerfile-bot

# Usar uma imagem base oficial do Python Alpine
FROM python:3.9-alpine

# Definir o diretório de trabalho
WORKDIR /app/telegram/bot

# Copiar arquivos de dependências do bot
COPY bot/requirements.txt .

# Instalar dependências do bot
RUN apk add --no-cache --virtual .build-deps gcc musl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-deps

# Copiar o código do bot
COPY bot/ .

# Comando para rodar o bot
CMD ["python", "teletriade3.py"]
